# CS 115 - Introduction to Programming in Python
## Lab 06 
### Objectives: Two-dimensional lists.  Numpy arrays.

**Instructions:**

- In this lab, you will use Jupyter Notebook. 
- Complete the questions in the spaces provided and upload the solution to Moodle when finished.

## Question 1
a) Write a function, find_max, that takes a 2 dimensional list of strings as a parameter.  For each column in the list, the function should replace the maximum string with an asterisk, and return a list containing the maximum string from each column.



In [96]:
ol=[['star', 'tree', 'flower', 'apple'], ['popcorn', 'snow', 'banana', 'radio'], ['candle', 'water', 'zebra', 'animal']]
def find_max(td):
    max_values=[]
    for c in range(len(td[0])):
        max_str=''
        max_row=0
        max_col=0
        for r in range(len(td)):
            if td[r][c]>max_str:
                max_row=r
                max_col=c
                max_str=td[r][c]
        max_values.append(td[max_row][max_col])
        td[max_row][max_col]='*'
        
    return max_values


        
            
        

In [97]:

print("Original List:")
print(ol)
print("Updated List:")
find_max(ol)
for l in ol:
    for i in l:
        print(i,end=' ')
    print()
print("Maximum values:",find_max(ol))

Original List:
[['star', 'tree', 'flower', 'apple'], ['popcorn', 'snow', 'banana', 'radio'], ['candle', 'water', 'zebra', 'animal']]
Updated List:
* tree flower apple 
popcorn snow banana * 
candle * * animal 
Maximum values: ['popcorn', 'tree', 'flower', 'apple']


## Question 2:
***Complete the following using numpy.  Do not use if statements or loops in your solution.***

#### a) Create a numpy array containing the names of 5 cities: 'Ankara', 'Istanbul', 'Konya', 'Izmir','Kayseri'

In [98]:
import numpy as np

cities=np.array(['Ankara','Istanbul','Konya','Izmir','Kayseri'])


#### b) Create a numpy array containing 5 random *float* values between 500 and 800 that represent the cost of heating in each of the cities above.

In [99]:

r_array20=np.random.randint(0,300,5)*np.random.rand(5)+500
print(r_array20)


[517.29749305 615.5422489  502.859141   587.23138703 740.62452237]


#### c) Create a two-dimensional numpy array with 3 rows and 5 columns. The first row will contain the heating costs for each city for 2020, the second row will contain the heating costs for 2021 (heating costs from 2020 increased by 20%), and the third row contains the costs for 2022 (heating costs from 2021 increased by 15%).

In [100]:

r_array21=r_array20*1.2
r_array22=r_array21*1.15
new_array=np.array([r_array20,r_array21,r_array22])
print(new_array)

[[ 517.29749305  615.5422489   502.859141    587.23138703  740.62452237]
 [ 620.75699166  738.65069868  603.4309692   704.67766443  888.74942684]
 [ 713.87054041  849.44830348  693.94561458  810.3793141  1022.06184087]]


#### d) Display the maximum heating cost for each year for all cities, and the average heating cost for each city, for all years.

In [101]:
import numpy as np
print("Max heating cost for each year:",np.max(new_array,axis=1))
print("Average heating cost for each city:",np.mean(new_array,axis=0))


Max heating cost for each year: [ 740.62452237  888.74942684 1022.06184087]
Average heating cost for each city: [617.30834171 734.54708368 600.07857493 700.76278852 883.81193003]


#### e) Display the names of the cities with the 2022 heating costs over 900.

In [102]:
index=np.where(r_array22>900)
print("Name of cities in 2022 over 900",cities[index])

Name of cities in 2022 over 900 ['Kayseri']
